project:
  type: website

website:
  google-analytics: "G-CMJVF1Q108"
  title: "Tina's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Analysis"
        menu:
          - text: "R Visual"
            href: "Analysis/R_Visual/R_Visual.html"
           
      - text: "Marketing"
        menu:
          - text: "Product Analysis"
            href: "Marketing/3M.html"
          - text: "Online Campaign"
            href: "Marketing/Online.html"
            
            
    right:
      - icon: github
        href: https://github.com/yenyunhsuan?tab=repositories
   
      - icon: linkedin
        href: https://www.linkedin.com/in/tina-yen/

      - icon: envelope
        href: mailto:tina.yen.yunhsuan@gmail.com
          

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    fontsize: 1.1em
    linestretch: 1.5
    scripts:
      - src: "links.js"

editor: visual

